name: continuous-integration
on: push

defaults:
  run:
    shell: pwsh

jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: latest
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: aa-exec --profile=chrome -- ./invoke.ps1 Client/Test
  server:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9
      - name: Run tests
        run: ./invoke.ps1 Server/Test
