name: continuous-integration
on: push

jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: latest
      - name: Install dependencies
        run: |
          dotnet tool restore
          npm ci
      - name: Run tests
        run: aa-exec --profile=chrome -- dotnet cake --target=test:client
  server:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9
      - name: Install dependencies
        run: dotnet tool restore
      - name: Run tests
        run: dotnet cake --target=test:server
